[server]
headless = true
address = "127.0.0.1"
port = 8501
enableCORS = false
enableXsrfProtection = true
fileWatcherType = "none"
maxUploadSize = 200

[browser]
gatherUsageStats = false
serverAddress = "127.0.0.1"
serverPort = 8501

[runner]
fastReruns = false
